# Site settings
title: Annelle de Jager
email: annelle.dejager@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  a collection of thoughts and experiences
baseurl: '/blog'  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
# twitter_username: twitter_username
github_username:  annelledejager

# Build settings
markdown: kramdown

highlighter: rouge

plugins:
  - jekyll-sitemap

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

comments: true

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  life:
    output: true
    permalink: /life/:path/
